version: "1"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "13307:3306"
    volumes:
      - ./.docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: t00r
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: passw0rd
#  app:
#    image: evermos/demo:1.0.0
#    environment:
#      DB_HOST: mysql
#      DB_USERNAME: demo
#      DB_PASSWORD: passw0rd
#      DB_PORT: 3306
#      DB_DATABASE: demo
#      LOG_MODE: INFO
#    ports:
#      - "9005:9005"
#      - "9095:9095"